oakmac/standard-clojure-style-js

lib/clojurefmt.js
test/format.test.js
test_format/format.eno

[Issue #9](https://github.com/oakmac/clojurefmt-js/issues/9)

add Rule 3 indentation

---

lib/clojurefmt.js
test/format.test.js
test_format/ns.eno

[Issue #5](https://github.com/oakmac/clojurefmt-js/issues/5)

GitHub Issue #5 - how to ns rules: use keywords, not symbols

---

lib/clojurefmt.js
test/format.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #5](https://github.com/oakmac/clojurefmt-js/issues/5)
* add `:refer-clojure`

Issue #5 - ns formatting

---

lib/clojurefmt.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #5](https://github.com/oakmac/clojurefmt-js/issues/5)
* support `:refer :all`
* support docstrings

Issue #5 - more namespace support

---

README.md
lib/clojurefmt.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #5](https://github.com/oakmac/clojurefmt-js/issues/5)
* handle comments inside of the `ns` form

Issue #5 - namespace comments

---

README.md
lib/clojurefmt.js
test/format.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #27](https://github.com/oakmac/clojurefmt-js/issues/27)

Issue #27 - :require-macros

---

lib/standard-clojure-style.js
test/format.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #26](https://github.com/oakmac/clojurefmt-js/issues/26)
- support reader conditionals with `:refer-clojure`

Issue #26 - reader conditionals inside :refer-clojure

---

lib/standard-clojure-style.js
test/format.test.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #31](https://github.com/oakmac/standard-clojure-style-js/issues/31)

Issue #31 - support :gen-class

---

lib/standard-clojure-style.js
test/format.test.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #26](https://github.com/oakmac/standard-clojure-style-js/issues/26)

Issue #26 - more work on :refer-clojure

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #41](https://github.com/oakmac/standard-clojure-style-js/issues/41)

Issue #41 - chessboard2 test cases

---

lib/standard-clojure-style.js
test_format/format.eno

[Issue #41](https://github.com/oakmac/standard-clojure-style-js/issues/41)

Issue #41 - more chessboard2 test cases

---

lib/standard-clojure-style.js
test_format/format.eno

Another test case from chessboard2, [Issue #41](https://github.com/oakmac/standard-clojure-style-js/issues/41)

Issue #41 test case

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #41](https://github.com/oakmac/standard-clojure-style-js/issues/41)
Another test case from chessboard2: comment alignment

Issue #41 - comment alignment

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #41](https://github.com/oakmac/standard-clojure-style-js/issues/41)
- related to comment indentation

Issue #41 - comment indentation

---

lib/standard-clojure-style.js
test/parse_ns.test.js
test_parse_ns/parse_ns.eno

[Issue #50](https://github.com/oakmac/standard-clojure-style-js/issues/50)

Issue #50 - ns parsing error

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #56](https://github.com/oakmac/standard-clojure-style-js/issues/56)

Issue #56 - nested rule 3 alignment

---

lib/standard-clojure-style.js
test_parser/token.eno

[Issue #63](https://github.com/oakmac/standard-clojure-style-js/issues/63)

Issue #63 - fix bug with comma character

---

cli.mjs
scripts/build-release.js

[Issue #67](https://github.com/oakmac/standard-clojure-style-js/issues/67)

GitHub Issue #67 - print the correct program version in the CLI tooling

---

lib/standard-clojure-style.js
test_format/format.eno

[Issue #68](https://github.com/oakmac/standard-clojure-style-js/issues/68)

Issue #68 - support tag literals

---

lib/standard-clojure-style.js
test_format/ns.eno

[Issue #76](https://github.com/oakmac/standard-clojure-style-js/issues/76)

GitHub Issue #76 bug with ns require-macros

---

lib/standard-clojure-style.js
test/format.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #74](https://github.com/oakmac/standard-clojure-style-js/issues/74)

Issue #74 - support require :exclude

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #75](https://github.com/oakmac/standard-clojure-style-js/issues/75)

Issue #75 - comments after ns form

---

lib/standard-clojure-style.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #69](https://github.com/oakmac/standard-clojure-style-js/issues/69)

Issue #69 support :as-alias

---

lib/standard-clojure-style.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #48](https://github.com/oakmac/standard-clojure-style-js/issues/48)

Issue #48 - refer-clojure rename with reader conditionals

---

lib/standard-clojure-style.js
test/internals.test.js
test_format/format.eno
test_format/ns.eno

[Issue #62](https://github.com/oakmac/standard-clojure-style-js/issues/62)

GitHub Issue #62 - put spaces around comments

---

lib/standard-clojure-style.js
test/internals.test.js
test_format/format.eno

[Issue #62](https://github.com/oakmac/standard-clojure-style-js/issues/62#issuecomment-2334589873)

GitHub Issue #62 - ensure space around comments

---

lib/standard-clojure-style.js

[Issue #93](https://github.com/oakmac/standard-clojure-style-js/issues/93)

GitHub Issue #93 - broader runtime support for objectForEach function

---

cli.mjs

[Issue #94](https://github.com/oakmac/standard-clojure-style-js/issues/94)

Issue94 add back shebang

---

lib/standard-clojure-style.js
test_format/format.eno
test_parser/token.eno

[Issue #97](https://github.com/oakmac/standard-clojure-style-js/issues/97)

GitHub Issue #97 - support whitespace characters in parser

---

lib/standard-clojure-style.js
test_format/format.eno

[Issue #99](https://github.com/oakmac/standard-clojure-style-js/issues/99)

GitHub Issue #99 - fix bug with parens inside of string literals

---

lib/standard-clojure-style.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #112](https://github.com/oakmac/standard-clojure-style-js/issues/112)
* support `:rename` in `:require` forms

Issue #112 support :rename in JS requires

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #110](https://github.com/oakmac/standard-clojure-style-js/issues/110)
* fix bug with tagged literal indentation

Issue #110 tagged literal alignment

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #6](https://github.com/oakmac/standard-clojure-style-js/issues/6)

Issue #6 - ability to ignore the next form

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno

[Issue #6](https://github.com/oakmac/standard-clojure-style-js/issues/6)
* support `:standard-clj/ignore-file` to ignore an entire file

Issue #6 - :standard-clj/ignore-file

---

lib/standard-clojure-style.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #126](https://github.com/oakmac/standard-clojure-style-js/issues/126)
* fix bug with parsing ns metadata

GitHub Issue #126 - fix bug with parsing ns metadata

---

lib/standard-clojure-style.js
test/format.test.js
test_format/format.eno
test_format/ns.eno

[Issue #87](https://github.com/oakmac/standard-clojure-style-js/issues/87)
* adjust `ns` indentation to match common community style
* wrap `:require` with a single reader conditional if all requires are for one platform

Issue #87 - ns indentation

---

lib/standard-clojure-style.js
test_format/format.eno

[Issue #137](https://github.com/oakmac/standard-clojure-style-js/issues/137)
* only process the first `ns` form

GitHub Issue #137 - only process the first ns form

---

lib/standard-clojure-style.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #142](https://github.com/oakmac/standard-clojure-style-js/issues/142)
* fix bug with reader conditionals and paren nesting levels

Issue #142 - ns bug with reader conditionals

---

lib/standard-clojure-style.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #166](https://github.com/oakmac/standard-clojure-style-js/issues/166)
* fix bug with `:require :refer :all :rename`

Issue #166 :refer :all :rename bug

---

lib/standard-clojure-style.js
test_format/format.eno

[Issue #165](https://github.com/oakmac/standard-clojure-style-js/issues/165)
* fix bug with comments and tag literal alignment

Issue #165 - bug with tag literal alignment

---

lib/standard-clojure-style.js
test/parse_ns.test.js
test_format/ns.eno
test_parse_ns/parse_ns.eno

[Issue #187](https://github.com/oakmac/standard-clojure-style-js/issues/187)
* fix bug with `:require :refer :rename`

Issue #187 - bug with  :require with :rename and :refer
